#ifndef _BASIC_GAME_CONSTANTS_H_
#define _BASIC_GAME_CONSTANTS_H_

#include "btBulletDynamicsCommon.h"

const int COORDINATE_DIMENSIONS = 3;
const int TEXTURE_COORDINATE_DIMENSIONS = 2;
const int NORMAL_VECTOR_COORIDINATES_DIMENSIONS = 3;
const int DIFFUSE_COLOR_DIMENSIONS = 4;
const int SPECULAR_COLOR_DIMENSIONS = 4;
const int VERTEX_ATTRIBUTE_NUMBER = COORDINATE_DIMENSIONS + TEXTURE_COORDINATE_DIMENSIONS + 
	NORMAL_VECTOR_COORIDINATES_DIMENSIONS + DIFFUSE_COLOR_DIMENSIONS + SPECULAR_COLOR_DIMENSIONS;
enum vertexAttributeIndices {COORDINATES, TEX_COORD, SURFACE_NORMAL, COLOR_DIFFUSE, COLOR_SPECULAR};
const btVector3 WORLD_GRAVITY(0, -9.80665, 0);
const int triangle_corners_per_square = 6;

#endif // !_BASIC_GAME_CONSTANTS_H_
